# Generated by Django 4.2.15 on 2024-08-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0014_merge_20240829_1335'),
        ('wibu_catalog', '0014_product_inventory'),
    ]

    operations = [
    ]
